In [1]:
# Importing important libraries
import numpy as np
import pandas as pd
import os #os → a built-in Python library for interacting with your Operating System (Windows, Linux, Mac).
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

In [ ]:
# 1. Clean olist_customers_dataset.csv dataset

In [2]:
# 1. Load dataset
df = pd.read_csv("olist_customers_dataset.csv")
df.head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG

In [3]:
# 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df.shape)

Shape : (99441, 5)

In [4]:
# shows all column names ->
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [5]:
# Cleaning up column names / string columns that have stray leading spaces
df.columns = df.columns.str.strip()
for c in df.select_dtypes(include = ["object", "string"]).columns:
    df[c] = df[c].str.strip()

# Adding a 'ID' column 
df.insert(0, "ID", range(len(df)))
df.head()

,ID,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [6]:
# Understand the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        99441 non-null  int64
 1   customer_id               99441 non-null  str
 2   customer_unique_id        99441 non-null  str
 3   customer_zip_code_prefix  99441 non-null  int64
 4   customer_city             99441 non-null  str
 5   customer_state            99441 non-null  str
dtypes: int64(2), str(4)
memory usage: 11.8 MB

In [ ]:
'''
Conclusions -> 
All the columns are in correct data types as expected.
'''

In [7]:
# Statistical summary
df.describe()

                 ID  customer_zip_code_prefix
count  99441.000000              99441.000000
mean   49720.000000              35137.474583
std    28706.288396              29797.938996
min        0.000000               1003.000000
25%    24860.000000              11347.000000
50%    49720.000000              24416.000000
75%    74580.000000              58900.000000
max    99440.000000              99990.000000

In [8]:
# Step 3 -> Number of unique values in categorical columns 
df[["customer_id", "customer_unique_id", "customer_city", "customer_state"]].nunique()

customer_id           99441
customer_unique_id    96096
customer_city          4119
customer_state           27
dtype: int64

In [9]:
df["customer_id"].unique()

<ArrowStringArray>
['06b8999e2fba1a1fbc88172c00ba8bc7', '18955e83d337fd6b2def6b18a428ac77',
 '4e7b3e00288586ebd08712fdd0374a03', 'b2b6027bc5c5109e529d4dc6358b12c3',
 '4f2d8ab171c80ec8364f7c12e35b23ad', '879864dab9bc3047522c92c82e1212b8',
 'fd826e7cf63160e536e0908c76c3f441', '5e274e7a0c3809e14aba7ad5aae0d407',
 '5adf08e34b2e993982a47070956c5c65', '4b7139f34592b3a31687243a302fa75b',
 ...
 'be842c57a8c5a62e9585dd72f22b6338', 'f255d679c7c86c24ef4861320d5b7675',
 '14308d2303a3e2bdf4939b86c46d2679', 'f5a0b560f9e9427792a88bec97710212',
 '7fe2e80252a9ea476f950ae8f85b0f8f', '17ddf5dd5d51696bb3d7c6291687be6f',
 'e7b71a9017aa05c9a7fd292d714858e8', '5e28dfe12db7fb50a4b2f691faecea5e',
 '56b18e2166679b8a959d72dd06da27f9', '274fa6071e5e17fe303b9748641082c8']
Length: 99441, dtype: str

In [10]:
# Step 4 -> Checking for missing values # Check missing values
df.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [11]:
# Step 5 -> Getting an idea about the number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
# np.int64(0) means that there are no duplicate rows in the dataset.

In [13]:
print("Duplicate rows :", df.duplicated().sum())

Duplicate rows : 0

In [14]:
# step 6 -> Save the cleaned CSV
df.to_csv("olist_customers_cleaned.csv", index=False)

In [15]:
# Check that the file was saved
print(os.path.exists("olist_customers_cleaned.csv"))

True

In [16]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 2. Clean olist_geolocation_dataset

In [42]:
# 1. Load dataset
df1 = pd.read_csv("olist_geolocation_dataset.csv")
df1.head(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP

In [34]:
# 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df1.shape)

Shape : (1000163, 5)

In [36]:
# Cleaning up column names / string columns that have stray leading spaces
df1.columns = df1.columns.str.strip()
for c in df1.select_dtypes(include = ["object", "string"]).columns:
    df1[c] = df1[c].str.strip()

# Adding a 'ID' column 
df1.insert(0, "ID", range(len(df1)))
df1.head()

,ID,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,0,1037,-23.545621,-46.639292,sao paulo,SP
1,1,1046,-23.546081,-46.644820,sao paulo,SP
2,2,1046,-23.546129,-46.642951,sao paulo,SP
3,3,1041,-23.544392,-46.639499,sao paulo,SP
4,4,1035,-23.541578,-46.641607,sao paulo,SP

In [37]:
# Understand the dataset
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 6 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   ID                           1000163 non-null  int64
 1   geolocation_zip_code_prefix  1000163 non-null  int64
 2   geolocation_lat              1000163 non-null  float64
 3   geolocation_lng              1000163 non-null  float64
 4   geolocation_city             1000163 non-null  str
 5   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(2), str(2)
memory usage: 58.0 MB

In [ ]:
'''
Conclusions -> 
All the columns are in correct data types as expected.
'''

In [38]:
# Statistical summary
df1.describe()

,ID,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng
count,1.000163e+06,1.000163e+06,1.000163e+06,1.000163e+06
mean,5.000810e+05,3.657417e+04,-2.117615e+01,-4.639054e+01
std,2.887223e+05,3.054934e+04,5.715866e+00,4.269748e+00
min,0.000000e+00,1.001000e+03,-3.660537e+01,-1.014668e+02
25%,2.500405e+05,1.107500e+04,-2.360355e+01,-4.857317e+01
50%,5.000810e+05,2.653000e+04,-2.291938e+01,-4.663788e+01
75%,7.501215e+05,6.350400e+04,-1.997962e+01,-4.376771e+01
max,1.000162e+06,9.999000e+04,4.506593e+01,1.211054e+02

In [39]:
# Step 3 -> Number of unique values in categorical columns 
df1[["geolocation_city", "geolocation_state"]].nunique()

geolocation_city     8010
geolocation_state      27
dtype: int64

In [40]:
# Step 4 -> Checking for missing values # Check missing values
df1.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [43]:
# Step 5 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df1.duplicated().sum())

Duplicate rows : 261831

In [44]:
# step 6 -> Remove duplicates
df1_clean = df1.drop_duplicates()

In [45]:
# step 7 -> Validate cleaning
print("Cleaned shape: ", df1_clean.shape)
print("Duplicates after cleaning :", df1.duplicated().sum())

Cleaned shape:  (738332, 5)
Duplicates after cleaning : 261831

In [ ]:
'''
Original rows       = 1,000,163
Columns             = 5
Missing values      = 0
Duplicate rows      = 261,831
Cleaned rows        = 738,332
Duplicate rows left = 0
''''

In [46]:
print(df1_clean.isnull().sum())

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [ ]:
# The dataset comes from the Brazilian e-commerce company Olist, and the geolocation_* columns contain locations in Brazil.

In [ ]:
'''
Brazil Coordinate ranges :
Latitude:  -33.75 to 5.27
Longitude: -73.99 to -34.79
'''

In [47]:
# step 8 -> is checking whether the latitude and longitude are geographically reasonable for Brazil

print("Before:", len(df1_clean))

in_brazil = (
    df1_clean["geolocation_lat"].between(-33.75, 5.27) &
    df1_clean["geolocation_lng"].between(-73.99, -34.79)
)

print("Removing:", (~in_brazil).sum())

df1_clean = df1_clean[in_brazil]

print("After:", len(df1_clean))

Before: 738332
Removing: 33
After: 738299

In [48]:
# step 9 -> this is another important data-cleaning step, called text normalization
import unicodedata
def clean_text(s): 
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode() 
    return s.lower().strip()
    
df1_clean["geolocation_city"] = df1_clean["geolocation_city"].apply(clean_text) 
print(df1_clean["geolocation_city"].nunique())

5962

In [49]:
df1_clean.groupby("geolocation_city")

In [50]:
df1_clean["geolocation_city"].value_counts()

geolocation_city
sao paulo           99646
rio de janeiro      35177
belo horizonte      19474
curitiba            11263
brasilia             8791
                    ...
barrado quarai          1
rolador                 1
sete de setembro        1
lajeado do bugre        1
padre gonzales          1
Name: count, Length: 5962, dtype: int64

In [51]:
df1_clean.shape

(738299, 5)

In [52]:
# step 10 -> This is an important step because you are changing the geolocation data from many rows per ZIP code into one row per ZIP code.
geo_clean = (
    df1_clean.groupby("geolocation_zip_code_prefix")             # groupby() + agg() is summarizing many records into one record per ZIP prefix.
      .agg(
          lat=("geolocation_lat", "mean"),
          lng=("geolocation_lng", "mean"),
          city=("geolocation_city", lambda s: s.mode()[0]),
          state=("geolocation_state", lambda s: s.mode()[0]),
      )
      .reset_index()
)

In [53]:
print(geo_clean.shape)

(19010, 5)

In [54]:
geo_clean.head(10)

   geolocation_zip_code_prefix        lat        lng       city state
0                         1001 -23.550227 -46.634039  sao paulo    SP
1                         1002 -23.547657 -46.634991  sao paulo    SP
2                         1003 -23.549000 -46.635582  sao paulo    SP
3                         1004 -23.549829 -46.634792  sao paulo    SP
4                         1005 -23.549547 -46.636406  sao paulo    SP
5                         1006 -23.550127 -46.636044  sao paulo    SP
6                         1007 -23.549962 -46.637204  sao paulo    SP
7                         1008 -23.546000 -46.635877  sao paulo    SP
8                         1009 -23.546891 -46.636498  sao paulo    SP
9                         1010 -23.546667 -46.635404  sao paulo    SP

In [55]:
# step 11 -> Save the cleaned CSV
geo_clean.to_csv("olist_geolocation_cleaned.csv", index=False)

In [56]:
# Check that the file was saved
print(os.path.exists("olist_customers_cleaned.csv"))

True

In [57]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 3. Clean olist_order_items_dataset

In [41]:
# step 1. Load dataset
df2 = pd.read_csv("olist_order_items_dataset.csv")
df2.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [42]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df2.shape)

Shape : (112650, 7)

In [43]:
# Cleaning up column names / string columns that have stray leading spaces
df2.columns = df2.columns.str.strip()
for c in df2.select_dtypes(include = ["object", "string"]).columns:
    df2[c] = df2[c].str.strip()

# Adding a 'ID' column 
df2.insert(0, "ID", range(len(df2)))
df2.head()

,ID,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [44]:
# Understand the dataset
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   112650 non-null  int64
 1   order_id             112650 non-null  str
 2   order_item_id        112650 non-null  int64
 3   product_id           112650 non-null  str
 4   seller_id            112650 non-null  str
 5   shipping_limit_date  112650 non-null  str
 6   price                112650 non-null  float64
 7   freight_value        112650 non-null  float64
dtypes: float64(2), int64(2), str(4)
memory usage: 19.3 MB

In [ ]:
'''
Conclusion -> 
shipping_limit_date should be in datetime
'''

In [45]:
# Step 3 -> Correcting the date columns to proper datetime dtype
df2["shipping_limit_date"] = pd.to_datetime(df2["shipping_limit_date"]).astype("datetime64[ns]")
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   112650 non-null  int64
 1   order_id             112650 non-null  str
 2   order_item_id        112650 non-null  int64
 3   product_id           112650 non-null  str
 4   seller_id            112650 non-null  str
 5   shipping_limit_date  112650 non-null  datetime64[ns]
 6   price                112650 non-null  float64
 7   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), str(3)
memory usage: 17.2 MB

In [46]:
# Statistical summary
df2.describe()

,ID,order_item_id,shipping_limit_date,price,freight_value
count,112650.000000,112650.000000,112650,112650.000000,112650.000000
mean,56324.500000,1.197834,2018-01-07 15:36:52.192685312,120.653739,19.990320
min,0.000000,1.000000,2016-09-19 00:15:34,0.850000,0.000000
25%,28162.250000,1.000000,2017-09-20 20:57:27.500000,39.900000,13.080000
50%,56324.500000,1.000000,2018-01-26 13:59:35,74.990000,16.260000
75%,84486.750000,1.000000,2018-05-10 14:34:00.750000128,134.900000,21.150000
max,112649.000000,21.000000,2020-04-09 22:35:08,6735.000000,409.680000
std,32519.398249,0.705124,NaN,183.633928,15.806405

In [47]:
# Step 4 -> Number of unique values in categorical columns 
df2[["order_id", "product_id", "seller_id"]].nunique()

order_id      98666
product_id    32951
seller_id      3095
dtype: int64

In [48]:
# Step 5 -> Checking for missing values # Check missing values
df2.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [49]:
# Step 6 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df2.duplicated().sum())

Duplicate rows : 0

In [ ]:
# np.int64(0) means that there are no duplicate rows in the dataset.

In [50]:
print("Rows:", len(df2))
print("Unique orders:", df2["order_id"].nunique())

Rows: 112650
Unique orders: 98666

In [51]:
print(df2.duplicated(["order_id", "order_item_id"]).sum())

0

In [52]:
# Step 7 -> Add a useful column
df2["total_value"] = df2["price"] + df2["freight_value"]

# This gives the total the customer paid for each item, product plus shipping, and you'll use it for revenue analysis.

In [53]:
df2.head()

,ID,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_value
0,0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04

In [54]:
# step 8 -> Save the cleaned CSV
df2.to_csv("olist_order_items_cleaned.csv", index=False)

In [55]:
# Check that the file was saved
print(os.path.exists("olist_order_items_cleaned.csv"))

True

In [56]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 4. clean olist_order_payments_dataset

In [74]:
# step 1. Load dataset
df3 = pd.read_csv("olist_order_payments_dataset.csv")
df3.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [75]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df3.shape)

Shape : (103886, 5)

In [76]:
# Cleaning up column names / string columns that have stray leading spaces
df3.columns = df3.columns.str.strip()
for c in df3.select_dtypes(include = ["object", "string"]).columns:
    df3[c] = df3[c].str.strip()

# Adding a 'ID' column 
df3.insert(0, "ID", range(len(df3)))
df3.head()

,ID,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [77]:
# Understand the dataset
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    103886 non-null  int64
 1   order_id              103886 non-null  str
 2   payment_sequential    103886 non-null  int64
 3   payment_type          103886 non-null  str
 4   payment_installments  103886 non-null  int64
 5   payment_value         103886 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 8.9 MB

In [ ]:
'''
Conclusions -> 
All the columns are in correct data types as expected.
'''

In [78]:
# Statistical summary
df3.describe()

                 ID  payment_sequential  payment_installments  payment_value
count  103886.00000       103886.000000         103886.000000  103886.000000
mean    51942.50000            1.092679              2.853349     154.100380
std     29989.44937            0.706584              2.687051     217.494064
min         0.00000            1.000000              0.000000       0.000000
25%     25971.25000            1.000000              1.000000      56.790000
50%     51942.50000            1.000000              1.000000     100.000000
75%     77913.75000            1.000000              4.000000     171.837500
max    103885.00000           29.000000             24.000000   13664.080000

In [79]:
# Step 3 -> Number of unique values in categorical columns 
df3[["order_id", "payment_type"]].nunique()

order_id        99440
payment_type        5
dtype: int64

In [80]:
# Step 4 -> Checking for missing values # Check missing values
df3.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [81]:
# Step 6 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df3.duplicated().sum())

Duplicate rows : 0

In [82]:
print(df3["payment_type"].value_counts())

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [83]:
# Step 7 -> Understand what one row means
print("Rows:", len(df3))
print("Unique orders:", df3["order_id"].nunique())

Rows: 103886
Unique orders: 99440

In [84]:
# Step 8 -> Remove zero-value payments
df3 = df3[df3["payment_value"] > 0] # This keeps only rows where the value is greater than 0
print("After removing zero payments:", df3.shape)

After removing zero payments: (103877, 6)

In [85]:
df3.head()

,ID,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [86]:
# step 8 -> Save the cleaned CSV
df3.to_csv("olist_order_payments_cleaned.csv", index=False)

In [87]:
# Check that the file was saved
print(os.path.exists("olist_order_payments_cleaned.csv"))

True

In [88]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 5. Clean olist_order_reviews_dataset

In [2]:
# step 1. Load dataset
df4 = pd.read_csv("olist_order_reviews_dataset.csv")
df4.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [3]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df4.shape)

Shape : (99224, 7)

In [4]:
# Cleaning up column names / string columns that have stray leading spaces
df4.columns = df4.columns.str.strip()
for c in df4.select_dtypes(include = ["object", "string"]).columns:
    df4[c] = df4[c].str.strip()

# Adding a 'ID' column 
df4.insert(0, "ID", range(len(df4)))
df4.head()

,ID,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [5]:
# Understand the dataset
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       99224 non-null  int64
 1   review_id                99224 non-null  str
 2   order_id                 99224 non-null  str
 3   review_score             99224 non-null  int64
 4   review_comment_title     11568 non-null  str
 5   review_comment_message   40977 non-null  str
 6   review_creation_date     99224 non-null  str
 7   review_answer_timestamp  99224 non-null  str
dtypes: int64(2), str(6)
memory usage: 18.6 MB

In [ ]:
'''
Conclusion -> 
review_creation_date and review_answer_timestamp should be in datetime
'''

In [6]:
# Step 3 -> Correcting the date columns to proper datetime dtype
df4["review_creation_date"] = pd.to_datetime(df4["review_creation_date"]).astype("datetime64[ns]")
df4["review_answer_timestamp"] = pd.to_datetime(df4["review_answer_timestamp"]).astype("datetime64[ns]")
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       99224 non-null  int64
 1   review_id                99224 non-null  str
 2   order_id                 99224 non-null  str
 3   review_score             99224 non-null  int64
 4   review_comment_title     11568 non-null  str
 5   review_comment_message   40977 non-null  str
 6   review_creation_date     99224 non-null  datetime64[ns]
 7   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(2), str(4)
memory usage: 15.0 MB

In [7]:
# Statistical summary
df4.describe()

,ID,review_score,review_creation_date,review_answer_timestamp
count,99224.000000,99224.000000,99224,99224
mean,49611.500000,4.086421,2018-01-12 20:49:23.948238336,2018-01-16 00:23:56.977938688
min,0.000000,1.000000,2016-10-02 00:00:00,2016-10-07 18:32:28
25%,24805.750000,4.000000,2017-09-23 00:00:00,2017-09-27 01:53:27.249999872
50%,49611.500000,5.000000,2018-02-02 00:00:00,2018-02-04 22:41:47.500000
75%,74417.250000,5.000000,2018-05-16 00:00:00,2018-05-20 12:11:21.500000
max,99223.000000,5.000000,2018-08-31 00:00:00,2018-10-29 12:27:35
std,28643.645892,1.347579,NaN,NaN

In [8]:
# Step 4 -> Number of unique values in categorical columns 
df4[["review_id", "order_id", "review_comment_title", "review_comment_message"]].nunique()

review_id                 98410
order_id                  98673
review_comment_title       4179
review_comment_message    35617
dtype: int64

In [9]:
# Step 5 -> Checking for missing values # Check missing values
df4.isnull().sum().any()

np.True_

In [10]:
df4.isnull().sum()

ID                             0
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [11]:
# Check missing-value percentage -> This gives a better understanding than just counting.

missing_percentage = (df4.isnull().sum() / len(df4)) * 100

missing_table = pd.DataFrame({
    "Missing Count": df4.isnull().sum(),
    "Missing Percentage": missing_percentage
})

missing_table

                         Missing Count  Missing Percentage
ID                                   0            0.000000
review_id                            0            0.000000
order_id                             0            0.000000
review_score                         0            0.000000
review_comment_title             87656           88.341530
review_comment_message           58247           58.702532
review_creation_date                 0            0.000000
review_answer_timestamp              0            0.000000

In [12]:
# Step 6 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df4.duplicated().sum())

Duplicate rows : 0

In [13]:
# step 7 -> Clean text columns (convert missing values to empty strings)
text_columns = [
    "review_comment_title",
    "review_comment_message"
]

for col in text_columns:
    df4[col] = df4[col].fillna("")

In [14]:
print(df4[text_columns].isnull().sum())

review_comment_title      0
review_comment_message    0
dtype: int64

In [15]:
df4.isnull().sum()

ID                         0
review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [16]:
df4.head()

,ID,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,,,2018-01-18,2018-01-18 21:46:59
1,1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,,,2018-03-10,2018-03-11 03:05:13
2,2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,,,2018-02-17,2018-02-18 14:36:24
3,3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [17]:
# step 7 -> Keep one review per order (the latest)
df4 = df4.sort_values("review_answer_timestamp")
df4 = df4.drop_duplicates(subset="order_id", keep="last")
print("After one review per order:", df4.shape)

After one review per order: (98673, 8)

In [ ]:
"""
sort_values puts the reviews in time order, oldest first.
drop_duplicates(subset="order_id", keep="last") keeps only the last row for each order, meaning the most recent review, and removes the older ones.

I chose the latest. Now each order has exactly one review.
Row count: 98,673 (551 removed)

"""

In [106]:
df4.shape

(98673, 8)

In [107]:
# step 8 -> Save the cleaned CSV
df4.to_csv("olist_order_reviews_cleaned.csv", index=False)

In [108]:
# Check that the file was saved
print(os.path.exists("olist_order_reviews_cleaned.csv"))

True

In [109]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 6. Clean olist_orders_dataset

In [24]:
# step 1. Load dataset
df5 = pd.read_csv("olist_orders_dataset.csv")
df5.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [25]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df5.shape)

Shape : (99441, 8)

In [26]:
# Cleaning up column names / string columns that have stray leading spaces
df5.columns = df5.columns.str.strip()
for c in df5.select_dtypes(include = ["object", "string"]).columns:
    df5[c] = df5[c].str.strip()

# Adding a 'ID' column 
df5.insert(0, "ID", range(len(df5)))
df5.head()

,ID,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [27]:
# Understand the dataset
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             99441 non-null  int64
 1   order_id                       99441 non-null  str
 2   customer_id                    99441 non-null  str
 3   order_status                   99441 non-null  str
 4   order_purchase_timestamp       99441 non-null  str
 5   order_approved_at              99281 non-null  str
 6   order_delivered_carrier_date   97658 non-null  str
 7   order_delivered_customer_date  96476 non-null  str
 8   order_estimated_delivery_date  99441 non-null  str
dtypes: int64(1), str(8)
memory usage: 22.8 MB

In [ ]:
'''
Conclusion -> 
order_purchase_timestamp and order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, 
order_estimated_delivery_date should be in datetime
'''

In [28]:
# Step 3 -> Correcting the date columns to proper datetime dtype
df5["order_purchase_timestamp"] = pd.to_datetime(df5["order_purchase_timestamp"]).astype("datetime64[ns]")
df5["order_approved_at"] = pd.to_datetime(df5["order_approved_at"]).astype("datetime64[ns]")
df5["order_delivered_carrier_date"] = pd.to_datetime(df5["order_delivered_carrier_date"]).astype("datetime64[ns]")
df5["order_delivered_customer_date"] = pd.to_datetime(df5["order_delivered_customer_date"]).astype("datetime64[ns]")
df5["order_estimated_delivery_date"] = pd.to_datetime(df5["order_estimated_delivery_date"]).astype("datetime64[ns]")
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             99441 non-null  int64
 1   order_id                       99441 non-null  str
 2   customer_id                    99441 non-null  str
 3   order_status                   99441 non-null  str
 4   order_purchase_timestamp       99441 non-null  datetime64[ns]
 5   order_approved_at              99281 non-null  datetime64[ns]
 6   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 7   order_delivered_customer_date  96476 non-null  datetime64[ns]
 8   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), int64(1), str(3)
memory usage: 13.8 MB

In [29]:
# Statistical summary
df5.describe()

,ID,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441.000000,99441,99281,97658,96476,99441
mean,49720.000000,2017-12-31 08:43:12.776581120,2017-12-31 18:35:24.098800128,2018-01-04 21:49:48.138278656,2018-01-14 12:09:19.035542272,2018-01-24 03:08:37.730111232
min,0.000000,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00
25%,24860.000000,2017-09-12 14:46:19,2017-09-12 23:24:16,2017-09-15 22:28:50.249999872,2017-09-25 22:07:22.249999872,2017-10-03 00:00:00
50%,49720.000000,2018-01-18 23:04:36,2018-01-19 11:36:13,2018-01-24 16:10:58,2018-02-02 19:28:10.500000,2018-02-15 00:00:00
75%,74580.000000,2018-05-04 15:42:16,2018-05-04 20:35:10,2018-05-08 13:37:45,2018-05-15 22:48:52.249999872,2018-05-25 00:00:00
max,99440.000000,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00
std,28706.288396,NaN,NaN,NaN,NaN,NaN

In [30]:
# Step 4 -> Number of unique values in categorical columns 
df5[["order_id", "customer_id", "order_status"]].nunique()

order_id        99441
customer_id     99441
order_status        8
dtype: int64

In [31]:
df5["order_status"].unique()

<ArrowStringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [32]:
# Step 5 -> Checking for missing values # Check missing values
df5.isnull().sum().any()

np.True_

In [33]:
df5.isnull().sum()

ID                                  0
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
# Keep them because they can represent orders where the particular event/date never occurred.
"""
canceled → may not have delivery date
processing → may not have delivery date
unavailable → may not have delivery date
"""

In [34]:
# step 7 -> Add helpful columns
# flag orders with impossible date sequences # Detect impossible date sequences.
df5["date_issue"] = (
    (df5["order_delivered_carrier_date"] < df5["order_purchase_timestamp"]) |
    (df5["order_delivered_customer_date"] < df5["order_delivered_carrier_date"])
) # Detect impossible date sequences.

# delivery performance
df5["delivery_days"] = (
    df5["order_delivered_customer_date"] - df5["order_purchase_timestamp"]
).dt.days        # How many days did it take to deliver the order?

df5["estimated_days"] = (
    df5["order_estimated_delivery_date"] - df5["order_purchase_timestamp"]
).dt.days          # How many days was the estimated delivery period?

df5["delay_days"] = (
    df5["order_delivered_customer_date"] - df5["order_estimated_delivery_date"]
).dt.days         # How many days early/late was the actual delivery?

df5["is_late"] = (df5["delay_days"] > 0) # Quickly identify whether an order was late.

# month for trend charts
df5["purchase_month"] = df5["order_purchase_timestamp"].dt.to_period("M").astype(str)  # Group orders by month for trend analysis.

In [35]:
df5.head()

,ID,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,date_issue,delivery_days,estimated_days,delay_days,is_late,purchase_month
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,8.0,15,-8.0,False,2017-10
1,1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,13.0,19,-6.0,False,2018-07
2,2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,9.0,26,-18.0,False,2018-08
3,3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,13.0,26,-13.0,False,2017-11
4,4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,2.0,12,-10.0,False,2018-02

In [36]:
df5.groupby("purchase_month")["order_id"].count()

purchase_month
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
2017-03    2682
2017-04    2404
2017-05    3700
2017-06    3245
2017-07    4026
2017-08    4331
2017-09    4285
2017-10    4631
2017-11    7544
2017-12    5673
2018-01    7269
2018-02    6728
2018-03    7211
2018-04    6939
2018-05    6873
2018-06    6167
2018-07    6292
2018-08    6512
2018-09      16
2018-10       4
Name: order_id, dtype: int64

In [37]:
df5.shape

(99441, 15)

In [39]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             99441 non-null  int64
 1   order_id                       99441 non-null  str
 2   customer_id                    99441 non-null  str
 3   order_status                   99441 non-null  str
 4   order_purchase_timestamp       99441 non-null  datetime64[ns]
 5   order_approved_at              99281 non-null  datetime64[ns]
 6   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 7   order_delivered_customer_date  96476 non-null  datetime64[ns]
 8   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 9   date_issue                     99441 non-null  bool
 10  delivery_days                  96476 non-null  float64
 11  estimated_days                 99441 non-null  int64
 12  delay_days                     96476 non-null  float64
 13  is_late                        99441 non-null  bool
 14  purchase_month                 99441 non-null  str
dtypes: bool(2), datetime64[ns](5), float64(2), int64(2), str(4)
memory usage: 17.7 MB

In [40]:
df5.head()

,ID,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,date_issue,delivery_days,estimated_days,delay_days,is_late,purchase_month
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,8.0,15,-8.0,False,2017-10
1,1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,13.0,19,-6.0,False,2018-07
2,2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,9.0,26,-18.0,False,2018-08
3,3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,13.0,26,-13.0,False,2017-11
4,4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,2.0,12,-10.0,False,2018-02

In [151]:
# step 8 -> Save the cleaned CSV
df5.to_csv("olist_orders_cleaned.csv", index=False)

In [152]:
# Check that the file was saved
print(os.path.exists("olist_orders_cleaned.csv"))

True

In [153]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 7. Clean olist_products_dataset

In [181]:
# step 1. Load dataset
df6 = pd.read_csv("olist_products_dataset.csv")
df6.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [155]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df6.shape)

Shape : (32951, 9)

In [182]:
# Cleaning up column names / string columns that have stray leading spaces
df6.columns = df6.columns.str.strip()
for c in df6.select_dtypes(include = ["object", "string"]).columns:
    df6[c] = df6[c].str.strip()

# Adding a 'ID' column 
df6.insert(0, "ID", range(len(df6)))
df6.head()

,ID,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [183]:
# Step 3. Fix the column name typo
df6 = df6.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length",
})

In [184]:
# Understand the dataset
df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          32951 non-null  int64
 1   product_id                  32951 non-null  str
 2   product_category_name       32341 non-null  str
 3   product_name_length         32341 non-null  float64
 4   product_description_length  32341 non-null  float64
 5   product_photos_qty          32341 non-null  float64
 6   product_weight_g            32949 non-null  float64
 7   product_length_cm           32949 non-null  float64
 8   product_height_cm           32949 non-null  float64
 9   product_width_cm            32949 non-null  float64
dtypes: float64(7), int64(1), str(2)
memory usage: 4.0 MB

In [ ]:
# Converts the length and photo columns to whole numbers

In [185]:
count_cols = ["product_name_length", "product_description_length", "product_photos_qty"]
df6[count_cols] = df6[count_cols].astype("Int64")

In [186]:
# recheck
df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          32951 non-null  int64
 1   product_id                  32951 non-null  str
 2   product_category_name       32341 non-null  str
 3   product_name_length         32341 non-null  Int64
 4   product_description_length  32341 non-null  Int64
 5   product_photos_qty          32341 non-null  Int64
 6   product_weight_g            32949 non-null  float64
 7   product_length_cm           32949 non-null  float64
 8   product_height_cm           32949 non-null  float64
 9   product_width_cm            32949 non-null  float64
dtypes: Int64(3), float64(4), int64(1), str(2)
memory usage: 4.1 MB

In [187]:
# Statistical summary
df6.describe()

,ID,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951.000000,32341.0,32341.0,32341.0,32949.000000,32949.000000,32949.000000,32949.000000
mean,16475.000000,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,9512.278697,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,0.000000,5.0,4.0,1.0,0.000000,7.000000,2.000000,6.000000
25%,8237.500000,42.0,339.0,1.0,300.000000,18.000000,8.000000,15.000000
50%,16475.000000,51.0,595.0,1.0,700.000000,25.000000,13.000000,20.000000
75%,24712.500000,57.0,972.0,3.0,1900.000000,38.000000,21.000000,30.000000
max,32950.000000,76.0,3992.0,20.0,40425.000000,105.000000,105.000000,118.000000

In [188]:
# Step 4 -> Number of unique values in categorical columns 
df6[["product_id", "product_category_name"]].nunique()

product_id               32951
product_category_name       73
dtype: int64

In [189]:
# Step 5 -> Checking for missing values # Check missing values
df6.isnull().sum().any()

np.True_

In [190]:
df6.isnull().sum()

ID                              0
product_id                      0
product_category_name         610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [191]:
# Step 6: Handle the missing category
df6["product_category_name"] = df6["product_category_name"].fillna("unknown")
print(df6["product_category_name"].nunique())

74

In [ ]:
"""
These 610 products probably have sales attached. If you delete them, you lose those sales from your revenue analysis. 
Filling with "unknown" keeps them and lets you see how much revenue has no category.
"""

In [192]:
# Step 7: Add a helpful column
df6["product_volume_cm3"] = (
    df6["product_length_cm"] *
    df6["product_height_cm"] *
    df6["product_width_cm"]
)

In [ ]:
"""
Volume (length × height × width) lets you study how product size relates to shipping cost later. 
It is missing for the 2 products without dimensions.
"""

In [193]:
print(df6.shape)
print("Duplicate product_id:", df6["product_id"].duplicated().sum())
print(df6.isnull().sum())
print("Zero weights left:", (df6["product_weight_g"] == 0).sum())

(32951, 11)
Duplicate product_id: 0
ID                              0
product_id                      0
product_category_name           0
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
product_volume_cm3              2
dtype: int64
Zero weights left: 4

In [194]:
df6.head()

,ID,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
0,0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225.0,16.0,10.0,14.0,2240.0
1,1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000.0,30.0,18.0,20.0,10800.0
2,2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154.0,18.0,9.0,15.0,2430.0
3,3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371.0,26.0,4.0,26.0,2704.0
4,4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625.0,20.0,17.0,13.0,4420.0

In [197]:
# step 7 -> Check negative values
non_negative_cols = [
    "product_name_length",
    "product_description_length",
    "product_photos_qty",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in non_negative_cols:
    df6.loc[df6[col] < 0, col] = np.nan

In [198]:
print(df6.isna().sum())

ID                              0
product_id                      0
product_category_name           0
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
product_volume_cm3              2
dtype: int64

In [199]:
# step 8 -> Save the cleaned CSV
df6.to_csv("olist_products_cleaned.csv", index=False)

In [200]:
# Check that the file was saved
print(os.path.exists("olist_products_cleaned.csv"))

True

In [201]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 8. clean olist_sellers_dataset

In [2]:
# step 1. Load dataset
df7 = pd.read_csv("olist_sellers_dataset.csv")
df7.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [3]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df7.shape)

Shape : (3095, 4)

In [4]:
# Cleaning up column names / string columns that have stray leading spaces
df7.columns = df7.columns.str.strip()
for c in df7.select_dtypes(include = ["object", "string"]).columns:
    df7[c] = df7[c].str.strip()

# Adding a 'ID' column 
df7.insert(0, "ID", range(len(df7)))
df7.head()

,ID,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [5]:
# Understand the dataset
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3095 non-null   int64
 1   seller_id               3095 non-null   str
 2   seller_zip_code_prefix  3095 non-null   int64
 3   seller_city             3095 non-null   str
 4   seller_state            3095 non-null   str
dtypes: int64(2), str(3)
memory usage: 255.7 KB

In [ ]:
'''
Conclusions -> 
All the columns are in correct data types as expected.
'''

In [6]:
# Statistical summary
df7.describe()

                ID  seller_zip_code_prefix
count  3095.000000             3095.000000
mean   1547.000000            32291.059451
std     893.593867            32713.453830
min       0.000000             1001.000000
25%     773.500000             7093.500000
50%    1547.000000            14940.000000
75%    2320.500000            64552.500000
max    3094.000000            99730.000000

In [7]:
# Step 3 -> Number of unique values in categorical columns 
df7[["seller_id", "seller_city", "seller_state"]].nunique()

seller_id       3095
seller_city      611
seller_state      23
dtype: int64

In [8]:
# Step 4 -> Checking for missing values # Check missing values
df7.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [9]:
# Step 5 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df7.duplicated().sum())

Duplicate rows : 0

In [10]:
# Step 6 -> Look at the messy cities
odd = df7[df7["seller_city"].str.contains(r"[0-9@/\\,;()\-\.]")]
print(len(odd))
print(odd["seller_city"].tolist())

26
['lages - sc', 'auriflama/sp', 'sao paulo / sao paulo', '04482255', 'novo hamburgo, rio grande do sul, brasil', 'cariacica / es', 'sao paulo - sp', 'sbc/sp', "arraial d'ajuda (porto seguro)", 'santo andre/sao paulo', 'sp / sp', 'maua/sao paulo', 'mogi das cruzes / sp', 'rio de janeiro \\rio de janeiro', 'barbacena/ minas gerais', 'sao paulo - sp', 'andira-pr', 'rio de janeiro / rio de janeiro', 'pinhais/pr', 'ribeirao preto / sao paulo', 'carapicuiba / sao paulo', 'vendas@creditparts.com.br', 'sao sebastiao da grama/sp', 'sao paulo - sp', 'rio de janeiro, rio de janeiro, brasil', 'jacarei / sao paulo']

In [ ]:
# 26 city values contain strange characters

In [11]:
import re  # The function uses it to cut city names at /, , and -
import unicodedata

In [12]:
# step 7 -> Write a cleaning function
def clean_city(s):
    # remove accents, lowercase, trim spaces
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower().strip()

    # values that are not cities at all (zip codes, emails)
    if s.isdigit() or "@" in s:
        return None

    # keep only the part before  /  \  ,  or  " - "
    s = re.split(r"\s*[/\\,]\s*|\s+-\s+", s)[0]

    # remove text in brackets, e.g. "(porto seguro)"
    s = re.sub(r"\s*\(.*\)", "", s)

    # remove a state attached with a hyphen, e.g. "andira-pr"
    s = re.sub(r"-[a-z]{2}$", "", s)

    # fix known abbreviations
    return {"sbc": "sao bernardo do campo", "sp": "sao paulo"}.get(s.strip(), s.strip())

In [ ]:
"""
Each line handles one kind of mess:

1.normalize(...) removes accents (são becomes sao), then .lower().strip() handles case and spaces.
2.isdigit() and "@" catch the zip code and email. They aren't cities, so the function returns None (missing).
3.re.split(...) cuts the text at /, \, , or a spaced hyphen and keeps the first piece. novo hamburgo, rio grande do sul, brasil becomes novo hamburgo.
4.The last regex removes a hyphen followed by exactly two letters at the end. I only cut " - " with spaces in Step 4's split, 
so real hyphenated city names like embu-guacu stay safe, except a name ending in a two-letter piece, so check Step 6.
5.The small dictionary expands abbreviations.

"""

In [13]:
# step 8 -> Apply it
df7["seller_city"] = df7["seller_city"].apply(clean_city)
print("Missing cities:", df7["seller_city"].isnull().sum())
df7["seller_city"] = df7["seller_city"].fillna("unknown")

Missing cities: 2

In [14]:
# Check the result
print("Cities:", df7["seller_city"].nunique())
odd = df7[df7["seller_city"].str.contains(r"[0-9@/\\,;()\-\.]")]
print(odd["seller_city"].unique())

"""
The city count drops from 611 to about 587 (586 real cities plus unknown), and the odd-character list should be empty. 
If a real hyphenated city appears in the list, tell me and we'll add it as an exception.
"""

Cities: 587
<ArrowStringArray>
[]
Length: 0, dtype: str

"\nThe city count drops from 611 to about 587 (586 real cities plus unknown), and the odd-character list should be empty. \nIf a real hyphenated city appears in the list, tell me and we'll add it as an exception.\n"

In [15]:
# step 9 -> Save the cleaned CSV
df7.to_csv("olist_sellers_cleaned.csv", index=False)

In [16]:
# Check that the file was saved
print(os.path.exists("olist_sellers_cleaned.csv"))

True

In [17]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data

In [ ]:
# 9. clean product_category_name_translation

In [18]:
# step 1. Load dataset
df8 = pd.read_csv("product_category_name_translation.csv")
df8.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [19]:
# step 2. Inspect dataset -> (number of rows, number of columns)
print("Shape :", df8.shape)

Shape : (71, 2)

In [20]:
# Cleaning up column names / string columns that have stray leading spaces
df8.columns = df8.columns.str.strip()
for c in df8.select_dtypes(include = ["object", "string"]).columns:
    df8[c] = df8[c].str.strip()

# Adding a 'ID' column 
df8.insert(0, "ID", range(len(df8)))
df8.head()

   ID   product_category_name product_category_name_english
0   0            beleza_saude                 health_beauty
1   1  informatica_acessorios         computers_accessories
2   2              automotivo                          auto
3   3         cama_mesa_banho                bed_bath_table
4   4        moveis_decoracao               furniture_decor

In [21]:
# Understand the dataset
df8.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             71 non-null     int64
 1   product_category_name          71 non-null     str
 2   product_category_name_english  71 non-null     str
dtypes: int64(1), str(2)
memory usage: 4.1 KB

In [ ]:
'''
Conclusions -> 
All the columns are in correct data types as expected.
'''

In [22]:
# Step 3 -> Number of unique values in categorical columns 
df8[["product_category_name", "product_category_name_english"]].nunique()

product_category_name            71
product_category_name_english    71
dtype: int64

In [23]:
# Step 4 -> Checking for missing values # Check missing values
df8.isnull().sum().any()

np.False_

In [ ]:
# np.False_ means that there are no NULL values in the data.

In [24]:
# Step 5 -> Getting an idea about the number of duplicate rows
print("Duplicate rows :", df8.duplicated().sum())

Duplicate rows : 0

In [25]:
# Step 6 -> Check missing values
print(df8.isna().sum())

ID                               0
product_category_name            0
product_category_name_english    0
dtype: int64

In [27]:
# Step 7 -> Make English names chart-friendly (optional)
df8["category_label"] = (
    df8["product_category_name_english"]
    .str.replace("_", " ")
    .str.title()
)

In [28]:
df8.head()

,ID,product_category_name,product_category_name_english,category_label
0,0,beleza_saude,health_beauty,Health Beauty
1,1,informatica_acessorios,computers_accessories,Computers Accessories
2,2,automotivo,auto,Auto
3,3,cama_mesa_banho,bed_bath_table,Bed Bath Table
4,4,moveis_decoracao,furniture_decor,Furniture Decor

In [29]:
# step 8 -> Save the cleaned CSV
df8.to_csv("product_category_name_translation_cleaned.csv", index=False)

In [30]:
# Check that the file was saved
print(os.path.exists("product_category_name_translation_cleaned.csv"))

True

In [31]:
# getcwd() -> Get Current Working Directory
print(os.getcwd())

C:\Users\sowri\OneDrive\Desktop\AIML\Project\Cart2Insights\data